apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert
  namespace: ml-ops
spec:
  secretName: example-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - domain.example.com  #domain name

